const defaultJobs=[
 {id:1,role:'Kompletowanie zamówień',company:'SwiftBox',icon:'⌂',date:'Poniedziałek',day:'monday',time:'08:00–10:00',start:8,end:10,rate:30,area:'Wola',lat:52.231,lng:20.952,industry:'logistics',match:96,color:'#d8ead8',newness:6,experience:false,english:false,tasks:['Kompletowanie produktów','Pakowanie przesyłek','Kontrola etykiet']},
 {id:2,role:'Wsparcie recepcji',company:'WorkHub',icon:'▤',date:'Poniedziałek',day:'monday',time:'16:00–20:00',start:16,end:20,rate:34,area:'Śródmieście',lat:52.2318,lng:21.0088,industry:'office',match:94,color:'#c9efe0',newness:5,experience:false,english:true,tasks:['Witanie gości','Obsługa korespondencji','Wsparcie zespołu biurowego']},
 {id:3,role:'Obsługa wydarzenia',company:'Expo Crew',icon:'✦',date:'Poniedziałek',day:'monday',time:'17:00–20:00',start:17,end:20,rate:33,area:'Centrum',lat:52.2225,lng:21.0051,industry:'events',match:91,color:'#ffe0cf',newness:4,experience:false,english:false,tasks:['Rejestracja uczestników','Kierowanie gości','Wsparcie organizatorów']},
 {id:4,role:'Inwentaryzacja sklepu',company:'CountUp',icon:'◼',date:'Wtorek',day:'tuesday',time:'18:00–22:00',start:18,end:22,rate:31,area:'Powiśle',lat:52.236,lng:21.0315,industry:'retail',match:88,color:'#d9ddff',newness:3,experience:false,english:false,tasks:['Liczenie towaru','Skanowanie produktów','Porządkowanie ekspozycji']},
 {id:5,role:'Ankieter terenowy',company:'Insight Lab',icon:'◎',date:'Wtorek',day:'tuesday',time:'16:00–19:00',start:16,end:19,rate:35,area:'Muranów',lat:52.2496,lng:20.9938,industry:'field',match:85,color:'#f7d6df',newness:2,experience:true,english:false,tasks:['Prowadzenie krótkich ankiet','Wprowadzanie odpowiedzi','Raportowanie postępu']},
 {id:6,role:'Sortowanie przesyłek',company:'ParcelOne',icon:'⌂',date:'Środa',day:'wednesday',time:'07:00–11:00',start:7,end:11,rate:32,area:'Mokotów',lat:52.1934,lng:21.0262,industry:'logistics',match:82,color:'#e4efbb',newness:1,experience:false,english:false,tasks:['Sortowanie paczek','Przygotowanie wysyłek','Kontrola kodów']}
];
const defaultPrivateDetails={
 1:{address:'ul. Ordona 2A, 01-237 Warszawa',contactName:'Marek Zieliński',contactPhone:'+48 512 440 830',arrival:'Przyjdź 10 minut wcześniej. Wejdź wejściem B i zgłoś się na ochronie.',dressCode:'Wygodne, zakryte buty i ciemne spodnie. Kamizelkę zapewnia firma.',documents:'Dowód osobisty',instructions:'Na miejscu odbędziesz krótkie szkolenie ze skanera. Dostępna jest szafka na rzeczy osobiste.'},
 2:{address:'Rondo ONZ 1, 00-124 Warszawa, piętro 12',contactName:'Anna Lewandowska',contactPhone:'+48 501 820 144',arrival:'Bądź 15 minut wcześniej przy recepcji głównej. Powiedz, że jesteś z Flexo.',dressCode:'Smart casual: koszula lub gładki T-shirt, długie spodnie, czyste obuwie.',documents:'Dokument tożsamości ze zdjęciem',instructions:'Telefon powinien być wyciszony podczas obsługi recepcji. Przerwa 15 minut jest wliczona w czas pracy.'},
 3:{address:'Plac Defilad 1, 00-901 Warszawa, wejście od ul. Marszałkowskiej',contactName:'Julia Mazur',contactPhone:'+48 509 311 720',arrival:'Spotkanie zespołu 20 minut przed startem przy punkcie rejestracji.',dressCode:'Cały czarny strój bez widocznych logotypów.',documents:'Dowód osobisty',instructions:'Identyfikator i krótkofalówkę otrzymasz na miejscu. Nie opuszczaj stanowiska bez poinformowania koordynatora.'},
 4:{address:'ul. Zajęcza 15, 00-351 Warszawa',contactName:'Piotr Dąbek',contactPhone:'+48 574 090 215',arrival:'Przyjdź 10 minut wcześniej do wejścia pracowniczego od zaplecza.',dressCode:'Wygodne buty i neutralny, ciemny strój.',documents:'Dokument tożsamości',instructions:'Telefon z naładowaną baterią będzie potrzebny do aplikacji skanującej.'},
 5:{address:'ul. Andersa 24, 00-201 Warszawa, punkt startowy przy wejściu',contactName:'Karolina Wójcik',contactPhone:'+48 602 118 933',arrival:'Zbiórka 15 minut wcześniej przy oznaczonym stoisku Insight Lab.',dressCode:'Swobodny, schludny strój odpowiedni do pracy na zewnątrz.',documents:'Brak dodatkowych dokumentów',instructions:'W razie deszczu firma zapewnia pelerynę. Telefon służbowy otrzymasz od koordynatora.'},
 6:{address:'ul. Cybernetyki 21, 02-677 Warszawa, magazyn C',contactName:'Tomasz Kurek',contactPhone:'+48 518 730 662',arrival:'Przyjdź 15 minut wcześniej do portierni magazynu C.',dressCode:'Długie spodnie i zakryte, stabilne obuwie.',documents:'Dowód osobisty',instructions:'Rękawice i kamizelkę zapewnia firma. Na hali obowiązuje zakaz używania telefonu.'}
};
function getJobDetails(j){return{address:j.address||defaultPrivateDetails[j.id]?.address||`${j.area}, Warszawa — dokładny adres do uzupełnienia`,contactName:j.contactName||defaultPrivateDetails[j.id]?.contactName||'Koordynator zmiany',contactPhone:j.contactPhone||defaultPrivateDetails[j.id]?.contactPhone||'+48 500 000 000',arrival:j.arrival||defaultPrivateDetails[j.id]?.arrival||'Przyjdź 10 minut przed rozpoczęciem zmiany.',dressCode:j.dressCode||defaultPrivateDetails[j.id]?.dressCode||'Schludny, wygodny strój.',documents:j.documents||defaultPrivateDetails[j.id]?.documents||'Dokument tożsamości',instructions:j.instructions||defaultPrivateDetails[j.id]?.instructions||'Dodatkowe informacje otrzymasz od koordynatora.'}}
let jobs=JSON.parse(localStorage.getItem('flexo-jobs')||'null')||defaultJobs;
jobs.forEach(j=>{if(!j.ownerEmail)j.ownerEmail=j.company==='Expo Crew'?'firma@flexo.pl':`owner-${j.id}@flexo.pl`;if(j.applicants==null)j.applicants=({1:8,2:5,3:7,4:11,5:4,6:6}[j.id]||0)});
let userProfile=JSON.parse(localStorage.getItem('flexo-profile')||'null')||{firstName:'Łukasz',lastName:'Kowalski',city:'Warszawa',email:'lukasz@example.pl',phone:'+48 500 600 700',bio:'Dyspozycyjny pracownik z doświadczeniem w obsłudze wydarzeń i logistyce.',skills:['Obsługa klienta','Logistyka','Punktualność'],industries:'Logistyka, Eventy'};
let editingJobId=null;
let registeredUsers=JSON.parse(localStorage.getItem('flexo-users')||'null')||[{firstName:'Łukasz',lastName:'Kowalski',email:'lukasz@example.pl',password:'flexo123',role:'user'}];
if(!registeredUsers.some(u=>u.email==='admin@flexo.pl'))registeredUsers.push({firstName:'Administrator',lastName:'Flexo',email:'admin@flexo.pl',password:'admin123',role:'admin'});
if(!registeredUsers.some(u=>u.email==='firma@flexo.pl'))registeredUsers.push({firstName:'Expo',lastName:'Crew',email:'firma@flexo.pl',password:'firma123',role:'employer'});
let authUser=JSON.parse(localStorage.getItem('flexo-session')||'null'),pendingAuthAction=null;
let booked=JSON.parse(localStorage.getItem('flexo-booked')||'[1]'),activeDate='all',aiMatchedIds=null;
let userLocation={lat:52.2297,lng:21.0122,label:'Centrum Warszawy'};
let locationFilterEnabled=false,travelMode='transit',jobsMap=null,startMarker=null,radiusCircle=null,jobMapLayer=null,routeLine=null,selectedMapJobId=null,routeRequestId=0;
let filters={radius:10,minRate:0,industries:[],time:'all',noExperience:false,noEnglish:false,sort:'recommended'};
const FLEXO_COMMISSION_RATE=.12;
const grid=document.querySelector('#jobsGrid'),jobModal=document.querySelector('#jobModal'),filterModal=document.querySelector('#filterModal'),assistantModal=document.querySelector('#assistantModal');
function distanceKm(a,b){const R=6371,r=v=>v*Math.PI/180,dLat=r(b.lat-a.lat),dLng=r(b.lng-a.lng),x=Math.sin(dLat/2)**2+Math.cos(r(a.lat))*Math.cos(r(b.lat))*Math.sin(dLng/2)**2;return R*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))}
function jobDistance(j){return distanceKm(userLocation,{lat:j.lat,lng:j.lng})}
function estimateTravel(j){const km=jobDistance(j)*1.25,modes={walk:{speed:4.5,extra:0,label:'pieszo'},bike:{speed:15,extra:2,label:'rowerem'},transit:{speed:18,extra:8,label:'komunikacją'},car:{speed:28,extra:5,label:'samochodem'}},m=modes[travelMode];return{minutes:Math.max(3,Math.round(km/m.speed*60+m.extra)),label:m.label}}
function timeMatches(j){return filters.time==='all'||(filters.time==='morning'&&j.start<12)||(filters.time==='afternoon'&&j.start>=12&&j.start<17)||(filters.time==='evening'&&j.start>=17)}
function filteredJobs(){const q=document.querySelector('#searchInput').value.trim().toLowerCase();let list=jobs.filter(j=>j.active!==false&&(activeDate==='all'||activeDate===j.day)&&(aiMatchedIds===null||aiMatchedIds.includes(j.id))&&(j.role+' '+j.company+' '+j.area).toLowerCase().includes(q)&&(!locationFilterEnabled||jobDistance(j)<=filters.radius)&&j.rate>=filters.minRate&&(!filters.industries.length||filters.industries.includes(j.industry))&&timeMatches(j)&&(!filters.noExperience||!j.experience)&&(!filters.noEnglish||!j.english));const sorters={nearest:(a,b)=>jobDistance(a)-jobDistance(b),rate:(a,b)=>b.rate-a.rate,newest:(a,b)=>b.newness-a.newness,recommended:(a,b)=>b.match-a.match};return list.sort(sorters[filters.sort])}
function requirementLabel(j){if(j.english)return 'Angielski wymagany';if(j.experience)return 'Doświadczenie wymagane';return 'Bez doświadczenia'}
function renderJobs(){const list=filteredJobs();document.querySelector('#resultCount').textContent=list.length;grid.innerHTML=list.length?list.map(j=>{const trip=estimateTravel(j),travel=locationFilterEnabled?`<span>⌖ ${jobDistance(j).toFixed(1).replace('.',',')} km</span><span class="travel-time">~${trip.minutes} min ${trip.label}</span>`:'';return`<article class="job-card" data-id="${j.id}"><div class="job-cover" style="--cover:${j.color}"><div class="company-logo">${j.icon}</div><span class="match">${j.match}% DOPASOWANIA</span></div><div class="job-body"><h3>${j.role}</h3><span class="company">${j.company} · ${j.area}</span><div class="job-meta"><span>▣ ${j.date}, ${j.time}</span>${travel}<span class="requirement-tag">${requirementLabel(j)}</span></div><div class="job-footer"><div><strong>${j.rate*(j.end-j.start)} zł</strong><small> · ${j.rate} zł/h</small></div><button>${booked.includes(j.id)?'Zapisano ✓':'Zobacz'}</button></div></div></article>`}).join(''):'<div class="empty"><strong>Brak zmian spełniających kryteria</strong><br><br>Zmień grafik, zwiększ promień albo usuń część filtrów.</div>';document.querySelectorAll('.job-card').forEach(el=>el.onclick=()=>openJob(+el.dataset.id));renderFilterSummary()}
function renderFilterSummary(){const chips=[];if(aiMatchedIds!==null)chips.push('Wybrane przez AI');if(locationFilterEnabled)chips.push(`Lokalizacja · do ${filters.radius} km`);if(filters.minRate)chips.push(`Od ${filters.minRate} zł/h`);if(filters.industries.length)chips.push(`${filters.industries.length} branże`);if(filters.time!=='all')chips.push({morning:'Rano',afternoon:'Popołudnie',evening:'Wieczór'}[filters.time]);if(filters.noExperience)chips.push('Bez doświadczenia');if(filters.noEnglish)chips.push('Bez angielskiego');document.querySelector('#activeFilters').innerHTML=chips.map(x=>`<span class="filter-chip">${x}</span>`).join('');const badge=document.querySelector('#filterCount');badge.textContent=chips.length;badge.classList.toggle('visible',chips.length>0);const bar=document.querySelector('.location-bar');bar.classList.toggle('inactive',!locationFilterEnabled);document.querySelector('#locationLabel').textContent=locationFilterEnabled?`${userLocation.label} · do ${filters.radius} km`:'Lokalizacja wyłączona';document.querySelector('#clearLocation').hidden=!locationFilterEnabled;document.querySelector('#mapClearLocation').hidden=!locationFilterEnabled}
function openJob(id){const j=jobs.find(x=>x.id===id),d=getJobDetails(j),pay=j.rate*(j.end-j.start);const publicPart=`<div class="modal-hero" style="background:${j.color}"><div class="company-logo">${j.icon}</div><p class="eyebrow">${j.match}% DOPASOWANIA · ${jobDistance(j).toFixed(1).replace('.',',')} KM</p><h2>${j.role}</h2><p>${j.company} · ${j.area}</p></div><div class="modal-body"><div class="modal-details"><div class="detail"><small>Kiedy</small><strong>${j.date}<br>${j.time}</strong></div><div class="detail"><small>Wynagrodzenie</small><strong>${pay} zł<br>${j.rate} zł/h</strong></div></div>`;if(!authUser){jobModal.querySelector('#modalContent').innerHTML=publicPart+`<div class="guest-job-preview"><h3>Informacje ogólne</h3><p>Krótka, elastyczna zmiana w dzielnicy ${j.area}. Dokładny adres, kontakt do pracodawcy, obowiązki i instrukcje organizacyjne są dostępne po zalogowaniu.</p><div class="locked-details"><div class="lock-icon">🔒</div><strong>Szczegóły dostępne po zalogowaniu</strong><p>Założenie konta jest bezpłatne i nie zobowiązuje Cię do przyjęcia zmiany.</p></div><button class="login-details-button">Zaloguj się i zobacz szczegóły</button></div></div>`;jobModal.showModal();jobModal.querySelector('.login-details-button').onclick=()=>openAuth('login',()=>openJob(id));return}jobModal.querySelector('#modalContent').innerHTML=publicPart+`<div class="details-section"><h3>Miejsce i kontakt</h3><div class="private-details-grid"><div class="private-detail wide"><small>DOKŁADNY ADRES</small><strong>⌖ ${d.address}</strong></div><div class="private-detail"><small>OSOBA KONTAKTOWA</small><strong>${d.contactName}</strong></div><div class="private-detail"><small>TELEFON SŁUŻBOWY</small><strong><a href="tel:${d.contactPhone.replace(/\s/g,'')}">${d.contactPhone}</a></strong></div></div></div><div class="details-section"><h3>Przygotowanie do zmiany</h3><div class="instruction-list"><div class="instruction-row"><span>◷</span><div><strong>Przyjście</strong><small>${d.arrival}</small></div></div><div class="instruction-row"><span>♙</span><div><strong>Strój</strong><small>${d.dressCode}</small></div></div><div class="instruction-row"><span>▤</span><div><strong>Dokumenty</strong><small>${d.documents}</small></div></div><div class="instruction-row"><span>ⓘ</span><div><strong>Dodatkowe informacje</strong><small>${d.instructions}</small></div></div></div></div><div class="details-section"><h3>Zakres obowiązków</h3><ul>${j.tasks.map(t=>`<li>${t}</li>`).join('')}</ul><p><strong>Wymagania:</strong> ${requirementLabel(j)}</p></div><button class="book-button" data-book="${j.id}">${booked.includes(j.id)?'Anuluj zapis':'Biorę tę zmianę'}</button><p class="details-notice">Klikając przycisk, potwierdzasz znajomość szczegółów i gotowość do realizacji zmiany.</p></div>`;jobModal.showModal();jobModal.querySelector('[data-book]').onclick=()=>toggleBook(id)}
function toggleBook(id){booked=booked.includes(id)?booked.filter(x=>x!==id):[...booked,id];localStorage.setItem('flexo-booked',JSON.stringify(booked));jobModal.close();renderJobs();renderBooked();renderDashboardSummary();toast(booked.includes(id)?'Zmiana jest Twoja! Szczegóły znajdziesz w kalendarzu.':'Zapis na zmianę został anulowany.')}
function renderBooked(){const list=booked.map(id=>jobs.find(j=>j.id===id)).filter(Boolean);document.querySelector('#shiftCount').textContent=list.length;document.querySelector('#bookedList').innerHTML=list.length?list.map(j=>`<article class="booked-card"><div class="date-tile"><small>${j.date.slice(0,3).toUpperCase()}</small><strong>${j.start}</strong></div><div class="grow"><h3>${j.role}</h3><p>${j.company} · ${j.time} · ${j.area}</p><strong>${j.rate*(j.end-j.start)} zł</strong></div><button class="primary" onclick="openJob(${j.id})">Szczegóły</button></article>`).join(''):'<div class="empty">Nie masz jeszcze zaplanowanych zmian.</div>'}
function switchView(id){if(id==='admin'&&authUser?.role!=='admin'){toast('Panel administratora jest dostępny tylko dla administratorów.');id='discover'}if(id==='employer'&&!['employer','admin'].includes(authUser?.role)){toast('Panel pracodawcy wymaga konta firmowego.');id='discover'}document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active-view',v.id===id));document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===id));window.scrollTo({top:0,behavior:'smooth'})}
function toast(msg){const t=document.querySelector('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3200)}
function locateUser(showMapAfter=false){const status=document.querySelector('#geoStatus');status.textContent='Pobieram lokalizację…';if(!navigator.geolocation)return toast('Ta przeglądarka nie obsługuje geolokalizacji.');navigator.geolocation.getCurrentPosition(p=>{userLocation={lat:p.coords.latitude,lng:p.coords.longitude,label:'Twoja lokalizacja'};locationFilterEnabled=true;status.textContent=`Dokładność: ${Math.round(p.coords.accuracy)} m`;renderJobs();if(showMapAfter){if(filterModal.open)filterModal.close();if(!document.querySelector('#mapModal').open)openMap()}if(jobsMap){jobsMap.setView([userLocation.lat,userLocation.lng],13);updateMap()}toast('Lokalizacja została ustawiona — wybierz ofertę na mapie.')},()=>{status.textContent='Brak dostępu';toast('Zezwól przeglądarce na dostęp do lokalizacji.')},{enableHighAccuracy:true,timeout:10000,maximumAge:300000})}
function syncFilterForm(){document.querySelector('#radiusInput').value=filters.radius;document.querySelector('#radiusOutput').value=filters.radius;document.querySelector(`[name="rate"][value="${filters.minRate}"]`).checked=true;document.querySelectorAll('[name="industry"]').forEach(x=>x.checked=filters.industries.includes(x.value));document.querySelector('#timeFilter').value=filters.time;document.querySelector('#noExperience').checked=filters.noExperience;document.querySelector('#noEnglish').checked=filters.noEnglish}
function readFilterForm(){filters.radius=+document.querySelector('#radiusInput').value;filters.minRate=+document.querySelector('[name="rate"]:checked').value;filters.industries=[...document.querySelectorAll('[name="industry"]:checked')].map(x=>x.value);filters.time=document.querySelector('#timeFilter').value;filters.noExperience=document.querySelector('#noExperience').checked;filters.noEnglish=document.querySelector('#noEnglish').checked}
function clearFilters(){filters={...filters,radius:10,minRate:0,industries:[],time:'all',noExperience:false,noEnglish:false};syncFilterForm()}
function clearAiResults(){aiMatchedIds=null;renderJobs()}
function parseAssistant(text){const t=text.toLowerCase().replace(/,/g,' '),days={monday:/poniedział|poniedzial/,tuesday:/wtorek|wtorku/,wednesday:/środ|srod/};let day=Object.keys(days).find(k=>days[k].test(t));const windows=[...t.matchAll(/(?:od\s*)?(\d{1,2})(?::\d{2})?\s*(?:-|–|do)\s*(\d{1,2})(?::\d{2})?/g)].map(m=>[+m[1],+m[2]]);const after=t.match(/po\s+(\d{1,2})/),before=t.match(/(?:przed|do)\s+(\d{1,2})/);if(!windows.length&&after)windows.push([+after[1],24]);if(!windows.length&&before)windows.push([0,+before[1]]);const rateMatch=t.match(/(?:minimum|min\.?|od)\s*(\d{2})\s*zł/),radiusMatch=t.match(/(?:do|promieniu)\s*(\d{1,2})\s*km/);const industries=[];if(/biur|recepc/.test(t))industries.push('office');if(/event|wydarze/.test(t))industries.push('events');if(/sklep|retail|inwent/.test(t))industries.push('retail');if(/logisty|magaz|paczk|przesył/.test(t))industries.push('logistics');if(/teren|ankiet/.test(t))industries.push('field');return{day,windows,minRate:rateMatch?+rateMatch[1]:0,radius:radiusMatch?+radiusMatch[1]:null,industries}}
function assistantSearch(text){const p=parseAssistant(text);let matches=jobs.filter(j=>j.active!==false&&(!p.day||j.day===p.day)&&(!p.windows.length||p.windows.some(([a,b])=>j.start>=a&&j.end<=b))&&j.rate>=p.minRate&&(!p.radius||jobDistance(j)<=p.radius)&&(!p.industries.length||p.industries.includes(j.industry)));return{parsed:p,matches}}
function addChat(text,type){const el=document.createElement('div');el.className=`chat-message ${type}`;el.innerHTML=text;document.querySelector('#assistantChat').appendChild(el);document.querySelector('#assistantChat').scrollTop=99999;return el}
function handleAssistant(text){if(!text.trim())return;addChat(text,'user');const {parsed,matches}=assistantSearch(text);setTimeout(()=>{const understood=[parsed.day&&({monday:'poniedziałek',tuesday:'wtorek',wednesday:'środę'}[parsed.day]),parsed.windows.length&&parsed.windows.map(x=>`${x[0]}:00–${x[1]}:00`).join(' lub '),parsed.minRate&&`min. ${parsed.minRate} zł/h`,parsed.radius&&`do ${parsed.radius} km`].filter(Boolean).join(', ');const cards=matches.map(j=>`<div class="ai-result"><div><strong>${j.role}</strong><small>${j.date} · ${j.time} · ${j.area}</small></div><b>${j.rate} zł/h</b></div>`).join('');const msg=matches.length?`Rozumiem: <strong>${understood||'elastyczny grafik'}</strong>. Znalazłem ${matches.length} ${matches.length===1?'pasującą zmianę':'pasujące zmiany'}:${cards}<button class="show-ai-results">Pokaż te oferty</button>`:`Rozumiem: <strong>${understood||'podane preferencje'}</strong>. Nie mam teraz idealnego dopasowania. Spróbuj poszerzyć godziny albo promień.`;const el=addChat(msg,'bot');const btn=el.querySelector('.show-ai-results');if(btn)btn.onclick=()=>{aiMatchedIds=matches.map(j=>j.id);activeDate='all';document.querySelectorAll('.filter[data-filter]').forEach(x=>x.classList.toggle('active',x.dataset.filter==='all'));assistantModal.close();renderJobs();toast('Pokazuję oferty wybrane przez asystenta.')}} ,350)}
function openAssistant(){assistantModal.showModal();setTimeout(()=>document.querySelector('#assistantPrompt').focus(),100)}
function initials(){return `${userProfile.firstName[0]||''}${userProfile.lastName[0]||''}`.toUpperCase()}
function renderGreeting(){document.querySelector('#heroGreeting').textContent=authUser?.role==='user'?`Cześć, ${authUser.firstName}!`:'Cześć!'}
function renderDashboardSummary(){const now=new Date(),dateText=new Intl.DateTimeFormat('pl-PL',{weekday:'long',day:'numeric',month:'long'}).format(now),unclaimed=jobs.filter(j=>j.active!==false&&!booked.includes(j.id)),value=unclaimed.reduce((sum,j)=>sum+j.rate*(j.end-j.start),0),allActive=jobs.filter(j=>j.active!==false).length;document.querySelector('#currentDate').textContent=dateText.charAt(0).toUpperCase()+dateText.slice(1);document.querySelector('#potential').textContent=`${value.toLocaleString('pl-PL')} zł`;document.querySelector('#potentialMeta').textContent=`${unclaimed.length} ${unclaimed.length===1?'dostępna zmiana':'dostępnych zmian'} w tym tygodniu`;document.querySelector('#potentialBar').style.width=`${allActive?Math.round(unclaimed.length/allActive*100):0}%`}
function renderProfile(){renderGreeting();document.querySelectorAll('.sidebar-user .avatar,.mobile-header .avatar,.profile-avatar').forEach(x=>x.textContent=initials());document.querySelector('.sidebar-user strong').textContent=userProfile.firstName;document.querySelector('#profileFullName').textContent=`${userProfile.firstName} ${userProfile.lastName}`;document.querySelector('#profileCity').textContent=userProfile.city;document.querySelector('#profileBio').textContent=userProfile.bio||'Dodaj kilka słów o sobie.';document.querySelector('#profileEmail').textContent=userProfile.email;document.querySelector('#profilePhone').textContent=userProfile.phone;document.querySelector('#profileIndustries').textContent=userProfile.industries||'Nie wybrano';document.querySelector('#profileSkills').innerHTML=userProfile.skills.map(x=>`<span>${x}</span>`).join('')}
function openProfileEditor(){const f=document.querySelector('#profileForm');['firstName','lastName','city','email','phone','bio','industries'].forEach(k=>f.elements[k].value=userProfile[k]||'');f.elements.skills.value=userProfile.skills.join(', ');document.querySelector('#profileModal').showModal()}
function saveProfile(form){const d=new FormData(form);userProfile={firstName:d.get('firstName').trim(),lastName:d.get('lastName').trim(),city:d.get('city').trim(),email:d.get('email').trim(),phone:d.get('phone').trim(),bio:d.get('bio').trim(),skills:d.get('skills').split(',').map(x=>x.trim()).filter(Boolean),industries:d.get('industries').trim()};localStorage.setItem('flexo-profile',JSON.stringify(userProfile));renderProfile();document.querySelector('#profileModal').close();toast('Profil został zaktualizowany.')}
function saveJobs(){localStorage.setItem('flexo-jobs',JSON.stringify(jobs));renderJobs();renderAdminJobs()}
function jobBilling(j){const value=Math.round(j.rate*(j.end-j.start)),fee=Math.round(value*FLEXO_COMMISSION_RATE);return{value,fee,total:value+fee}}
function jobsManagementHtml(list){return list.map(j=>{const bill=jobBilling(j);return`<div class="admin-job-row"><div class="admin-job-icon">${j.icon}</div><div><strong>${j.role}</strong><small>${j.company} · ${j.date}, ${j.time} · ${j.rate} zł/h · ${j.applicants||0} zgłoszeń</small><div class="job-costs"><span><small>WARTOŚĆ ZLECENIA</small><b>${bill.value} zł</b></span><span class="fee"><small>PROWIZJA FLEXO · 12%</small><b>${bill.fee} zł</b></span><span class="total"><small>KOSZT ŁĄCZNY</small><b>${bill.total} zł</b></span></div></div><span class="status ${j.active===false?'paused':'active'}">${j.active===false?'Wstrzymana':'Aktywna'}</span><div class="admin-actions"><button class="preview-action" onclick="previewManagedJob(${j.id})" title="Podgląd zlecenia">◉</button><button onclick="editAdminJob(${j.id})" title="Edytuj">✎</button><button onclick="toggleAdminJob(${j.id})" title="${j.active===false?'Aktywuj':'Wstrzymaj'}">${j.active===false?'▶':'Ⅱ'}</button><button class="danger" onclick="deleteAdminJob(${j.id})" title="Usuń">×</button></div></div>`}).join('')}
function renderAdminJobs(){const adminQ=(document.querySelector('#adminJobSearch')?.value||'').toLowerCase(),employerQ=(document.querySelector('#employerJobSearch')?.value||'').toLowerCase(),matches=(j,q)=>(j.role+' '+j.company+' '+j.area).toLowerCase().includes(q),myJobs=jobs.filter(j=>j.ownerEmail===authUser?.email),activeJobs=jobs.filter(j=>j.active!==false),inactiveJobs=jobs.filter(j=>j.active===false),unclaimedJobs=activeJobs.filter(j=>!booked.includes(j.id)),myActive=myJobs.filter(j=>j.active!==false),sumApplicants=list=>list.reduce((sum,j)=>sum+(j.applicants||0),0),sumValue=list=>list.reduce((sum,j)=>sum+j.rate*(j.end-j.start),0),jobsValue=sumValue(activeJobs),inactiveValue=sumValue(inactiveJobs),unclaimedValue=sumValue(unclaimedJobs),allValue=jobsValue+inactiveValue,activeCommission=Math.round(jobsValue*FLEXO_COMMISSION_RATE),activeShare=allValue?Math.round(jobsValue/allValue*100):0;document.querySelector('#adminUsersCount').textContent=registeredUsers.length;document.querySelector('#adminJobsCount').textContent=activeJobs.length;document.querySelector('#adminJobsStatus').textContent=`${inactiveJobs.length} wstrzymanych`;document.querySelector('#adminApplicants').textContent=sumApplicants(jobs);document.querySelector('#adminJobsValue').textContent=`${jobsValue.toLocaleString('pl-PL')} zł`;document.querySelector('#adminActiveCommission').textContent=`${activeCommission.toLocaleString('pl-PL')} zł`;document.querySelector('#adminInactiveValue').textContent=`${unclaimedValue.toLocaleString('pl-PL')} zł`;document.querySelector('#adminActiveShare').textContent=`${activeShare}%`;document.querySelector('#employerTotalJobs').textContent=myJobs.length;document.querySelector('#employerJobsCount').textContent=myActive.length;document.querySelector('#employerJobsStatus').textContent=`${myJobs.length-myActive.length} wstrzymanych`;document.querySelector('#employerApplicants').textContent=sumApplicants(myJobs);document.querySelector('#employerFilled').textContent=myJobs.filter(j=>booked.includes(j.id)).length;document.querySelector('#adminJobsList').innerHTML=jobsManagementHtml(jobs.filter(j=>matches(j,adminQ)));document.querySelector('#employerJobsList').innerHTML=jobsManagementHtml(myJobs.filter(j=>matches(j,employerQ)))||'<div class="empty">Nie masz jeszcze własnych ofert. Kliknij „Dodaj ofertę”.</div>'}
function canManageJobs(){if(['employer','admin'].includes(authUser?.role))return true;toast('Ta funkcja jest dostępna tylko dla pracodawcy lub administratora.');return false}
function canManageJob(j){if(!canManageJobs())return false;if(authUser.role==='admin'||j?.ownerEmail===authUser.email)return true;toast('Pracodawca może zarządzać tylko własnymi ofertami.');return false}
function previewManagedJob(id){const j=jobs.find(x=>x.id===id);if(!canManageJob(j))return;const bill=jobBilling(j);openJob(id);jobModal.querySelector('.book-button')?.remove();jobModal.querySelector('.details-notice')?.remove();jobModal.querySelector('.modal-body')?.insertAdjacentHTML('beforeend',`<div class="management-preview-note">◉ Podgląd zlecenia w widoku pracownika</div><div class="billing-summary"><small>ROZLICZENIE PRACODAWCY</small><div><span>Wynagrodzenie pracownika</span><strong>${bill.value} zł</strong></div><div><span>Prowizja Flexo (12%)</span><strong>${bill.fee} zł</strong></div><div class="billing-total"><span>Łączny koszt zlecenia</span><strong>${bill.total} zł</strong></div></div>`)}
function adminRoleLabel(role){return{user:'Pracownik',employer:'Pracodawca',admin:'Administrator'}[role]||'Pracownik'}
function renderAdminDirectory(){const usersList=document.querySelector('#adminUsersList'),employersList=document.querySelector('#adminEmployersList');if(!usersList||!employersList)return;const workers=registeredUsers.filter(u=>(u.role||'user')==='user');usersList.innerHTML=workers.map((u,index)=>{const initials=`${u.firstName?.[0]||''}${u.lastName?.[0]||''}`.toUpperCase();return`<button class="directory-row" onclick="openAdminUser('${u.email}')"><span class="avatar">${initials}</span><span><strong>${u.firstName} ${u.lastName}</strong><small>Pracownik · ${u.email}</small></span><span class="status ${index===1?'pending':'active'}">${index===1?'Weryfikacja':'Aktywny'}</span><b>›</b></button>`}).join('')||'<div class="empty">Brak zarejestrowanych pracowników.</div>';const companies=new Map();jobs.forEach(j=>{const key=j.ownerEmail||'unknown',entry=companies.get(key)||{email:key,company:j.company,jobs:[]};entry.jobs.push(j);companies.set(key,entry)});const activeCompanies=[...companies.values()].filter(c=>c.jobs.some(j=>j.active!==false));employersList.innerHTML=activeCompanies.map(c=>{const active=c.jobs.filter(j=>j.active!==false).length,applicants=c.jobs.reduce((sum,j)=>sum+(j.applicants||0),0);return`<button class="directory-row employer-row" onclick="openAdminEmployer('${c.email}')"><span class="avatar blue">${c.company.slice(0,2).toUpperCase()}</span><span><strong>${c.company}</strong><small>${active} aktywnych ofert · ${applicants} zgłoszeń</small></span><span class="status active">Aktywny</span><b>›</b></button>`}).join('')||'<div class="empty">Brak aktywnych zleceniodawców.</div>'}
function showAdminDetails(html){if(authUser?.role!=='admin')return toast('Dane kont są dostępne tylko dla administratora.');document.querySelector('#adminDetailsContent').innerHTML=html;document.querySelector('#adminDetailsModal').showModal()}
function openAdminUser(email){const u=registeredUsers.find(x=>x.email===email);if(!u)return;const owned=jobs.filter(j=>j.ownerEmail===email),activity=u.role==='employer'?`${owned.length} ofert · ${owned.reduce((sum,j)=>sum+(j.applicants||0),0)} zgłoszeń`:u.role==='user'?`${booked.length} zapisanych zmian`:'Pełny dostęp administracyjny';showAdminDetails(`<div class="admin-detail-head"><div class="avatar large">${(u.firstName[0]+u.lastName[0]).toUpperCase()}</div><div><p class="eyebrow">${adminRoleLabel(u.role).toUpperCase()}</p><h2>${u.firstName} ${u.lastName}</h2><span class="status active">Konto aktywne</span></div></div><div class="admin-detail-grid"><div><small>E-MAIL</small><strong>${u.email}</strong></div><div><small>ROLA</small><strong>${adminRoleLabel(u.role)}</strong></div><div><small>WERYFIKACJA</small><strong>${u.role==='admin'?'Uprawnienia administratora':'Tożsamość potwierdzona'}</strong></div><div><small>AKTYWNOŚĆ</small><strong>${activity}</strong></div></div>`) }
function openAdminEmployer(email){const owned=jobs.filter(j=>j.ownerEmail===email);if(!owned.length)return;const active=owned.filter(j=>j.active!==false),company=owned[0].company,applicants=owned.reduce((sum,j)=>sum+(j.applicants||0),0),value=active.reduce((sum,j)=>sum+j.rate*(j.end-j.start),0);showAdminDetails(`<div class="admin-detail-head"><div class="avatar large blue">${company.slice(0,2).toUpperCase()}</div><div><p class="eyebrow">ZLECENIODAWCA</p><h2>${company}</h2><span class="status active">Aktywny</span></div></div><div class="admin-detail-grid"><div><small>KONTO / IDENTYFIKATOR</small><strong>${email}</strong></div><div><small>OFERTY</small><strong>${active.length} aktywnych · ${owned.length-active.length} wstrzymanych</strong></div><div><small>ZGŁOSZENIA</small><strong>${applicants}</strong></div><div><small>WARTOŚĆ AKTYWNYCH ZMIAN</small><strong>${value.toLocaleString('pl-PL')} zł</strong></div></div>`) }
function updateEmployerBilling(){const active=jobs.filter(j=>j.ownerEmail===authUser?.email&&j.active!==false),value=active.reduce((sum,j)=>sum+jobBilling(j).value,0),fee=active.reduce((sum,j)=>sum+jobBilling(j).fee,0);document.querySelector('#employerJobsValue').textContent=`${value.toLocaleString('pl-PL')} zł`;document.querySelector('#employerFlexoFee').textContent=`${fee.toLocaleString('pl-PL')} zł`}
const renderAdminJobsBase=renderAdminJobs;renderAdminJobs=function(){renderAdminJobsBase();renderAdminDirectory();updateEmployerBilling();renderGreeting();renderDashboardSummary()}
function toggleAdminJob(id){const j=jobs.find(x=>x.id===id);if(!canManageJob(j))return;j.active=j.active===false;saveJobs();toast(j.active?'Oferta została aktywowana.':'Oferta została wstrzymana.')}
function deleteAdminJob(id){const j=jobs.find(x=>x.id===id);if(!canManageJob(j)||!confirm('Usunąć tę ofertę?'))return;jobs=jobs.filter(x=>x.id!==id);booked=booked.filter(x=>x!==id);localStorage.setItem('flexo-booked',JSON.stringify(booked));saveJobs();renderBooked();toast('Oferta została usunięta.')}
function openNewJob(){if(!canManageJobs())return;editingJobId=null;const form=document.querySelector('#adminJobForm');form.reset();form.elements.start.value='09:00';form.elements.end.value='13:00';form.elements.rate.value='32';document.querySelector('#jobFormEyebrow').textContent='NOWA ZMIANA';document.querySelector('#jobFormTitle').textContent='Dodaj ofertę';document.querySelector('#jobFormSubmit').textContent='Opublikuj ofertę';document.querySelector('#jobFormModal').showModal()}
function editAdminJob(id){const j=jobs.find(x=>x.id===id);if(!canManageJob(j)||!j)return;editingJobId=id;const form=document.querySelector('#adminJobForm'),d=getJobDetails(j),clock=n=>`${String(Math.floor(n)).padStart(2,'0')}:${String(Math.round(n%1*60)).padStart(2,'0')}`;form.elements.role.value=j.role;form.elements.company.value=j.company;form.elements.area.value=j.area;form.elements.address.value=d.address;form.elements.contactName.value=d.contactName;form.elements.contactPhone.value=d.contactPhone;form.elements.day.value=j.day;form.elements.industry.value=j.industry;form.elements.start.value=clock(j.start);form.elements.end.value=clock(j.end);form.elements.rate.value=j.rate;form.elements.tasks.value=(j.tasks||[]).join(', ');form.elements.arrival.value=d.arrival;form.elements.dressCode.value=d.dressCode;form.elements.documents.value=d.documents;form.elements.instructions.value=d.instructions;document.querySelector('#jobFormEyebrow').textContent='EDYCJA OFERTY';document.querySelector('#jobFormTitle').textContent=j.role;document.querySelector('#jobFormSubmit').textContent='Zapisz zmiany';document.querySelector('#jobFormModal').showModal()}
function addAdminJob(form){if(!canManageJobs())return;const d=new FormData(form),days={monday:'Poniedziałek',tuesday:'Wtorek',wednesday:'Środa'},icons={office:'▤',events:'✦',retail:'◼',logistics:'⌂',field:'◎'},start=d.get('start'),end=d.get('end'),industry=d.get('industry');if(end<=start)return toast('Godzina zakończenia musi być późniejsza niż rozpoczęcia.');const values={role:d.get('role').trim(),company:d.get('company').trim(),icon:icons[industry],date:days[d.get('day')],day:d.get('day'),time:`${start}–${end}`,start:+start.split(':')[0]+(+start.split(':')[1]/60),end:+end.split(':')[0]+(+end.split(':')[1]/60),rate:+d.get('rate'),area:d.get('area').trim(),industry,tasks:d.get('tasks').split(',').map(x=>x.trim()).filter(Boolean),address:d.get('address').trim(),contactName:d.get('contactName').trim(),contactPhone:d.get('contactPhone').trim(),arrival:d.get('arrival').trim(),dressCode:d.get('dressCode').trim(),documents:d.get('documents').trim(),instructions:d.get('instructions').trim()};if(editingJobId){const edited=jobs.find(x=>x.id===editingJobId);if(!canManageJob(edited))return;Object.assign(edited,values)}else{jobs.unshift({id:Date.now(),...values,ownerEmail:authUser.email,applicants:0,lat:52.2297,lng:21.0122,match:90,color:'#dbeee6',newness:Date.now(),experience:false,english:false,active:true})}saveJobs();document.querySelector('#jobFormModal').close();form.reset();toast(editingJobId?'Zmiany w ofercie zostały zapisane.':'Nowa oferta została opublikowana.');editingJobId=null}
function switchAuthTab(tab){document.querySelectorAll('[data-auth-tab]').forEach(b=>b.classList.toggle('active',b.dataset.authTab===tab));document.querySelector('#loginForm').classList.toggle('hidden',tab!=='login');document.querySelector('#registerForm').classList.toggle('hidden',tab!=='register');document.querySelector('#loginError').textContent='';document.querySelector('#registerError').textContent=''}
function openAuth(tab='login',action=null){pendingAuthAction=action;if(jobModal.open)jobModal.close();switchAuthTab(tab);document.querySelector('#authModal').showModal();setTimeout(()=>document.querySelector(`#${tab}Form input`).focus(),100)}
function requireAuth(action){if(authUser)return action();openAuth('login',action)}
function finishAuth(user){authUser={firstName:user.firstName,lastName:user.lastName,email:user.email,role:user.role||'user'};localStorage.setItem('flexo-session',JSON.stringify(authUser));document.querySelector('#authModal').close();renderAuthState();renderAdminJobs();toast(`Witaj, ${user.firstName}!`);const action=pendingAuthAction;pendingAuthAction=null;if(authUser.role==='employer')switchView('employer');else if(authUser.role==='admin')switchView('admin');else if(action)setTimeout(action,150);else switchView('discover')}
function login(form){const d=new FormData(form),email=d.get('email').trim().toLowerCase(),user=registeredUsers.find(x=>x.email.toLowerCase()===email&&x.password===d.get('password'));if(!user){document.querySelector('#loginError').textContent='Nieprawidłowy e-mail lub hasło.';return}finishAuth(user);form.reset()}
function register(form){const d=new FormData(form),email=d.get('email').trim().toLowerCase();if(registeredUsers.some(x=>x.email.toLowerCase()===email)){document.querySelector('#registerError').textContent='Konto z tym adresem już istnieje.';return}const user={firstName:d.get('firstName').trim(),lastName:d.get('lastName').trim(),email,password:d.get('password'),role:'user'};registeredUsers.push(user);localStorage.setItem('flexo-users',JSON.stringify(registeredUsers));userProfile={...userProfile,firstName:user.firstName,lastName:user.lastName,email:user.email};localStorage.setItem('flexo-profile',JSON.stringify(userProfile));renderProfile();finishAuth(user);form.reset()}
function renderAuthState(){const sidebar=document.querySelector('.sidebar-user'),mobile=document.querySelector('#mobileAccountAction'),isAdmin=authUser?.role==='admin',isEmployer=authUser?.role==='employer',workerViews=['discover','schedule','wallet','profile'];document.querySelectorAll('[data-view="admin"]').forEach(x=>x.hidden=!isAdmin);document.querySelectorAll('[data-view="employer"]').forEach(x=>x.hidden=!isEmployer);document.querySelectorAll('[data-view]').forEach(x=>{if(workerViews.includes(x.dataset.view))x.hidden=isAdmin||isEmployer});if(!isAdmin&&document.querySelector('#admin').classList.contains('active-view'))switchView(isEmployer?'employer':'discover');if(!isEmployer&&document.querySelector('#employer').classList.contains('active-view'))switchView(isAdmin?'admin':'discover');if(authUser){const roleLabel=isAdmin?'Administrator':isEmployer?'Pracodawca':userProfile.city,avatar=isAdmin?'AF':isEmployer?'EC':initials();sidebar.classList.remove('guest');sidebar.querySelector('strong').textContent=authUser.firstName;sidebar.querySelector('small').textContent=roleLabel;sidebar.querySelector('.avatar').textContent=avatar;document.querySelector('#accountAction').textContent='Wyjdź';document.querySelector('#accountAction').title='Wyloguj się';mobile.classList.remove('guest');mobile.textContent=avatar}else{sidebar.classList.add('guest');sidebar.querySelector('strong').textContent='Gość';sidebar.querySelector('small').textContent='Przeglądasz bez konta';sidebar.querySelector('.avatar').textContent='?';document.querySelector('#accountAction').textContent='Zaloguj';document.querySelector('#accountAction').title='Zaloguj się';mobile.classList.add('guest');mobile.textContent='?'}}
function accountAction(){if(!authUser)return openAuth();if(confirm('Czy chcesz się wylogować?')){authUser=null;localStorage.removeItem('flexo-session');renderAuthState();renderAdminJobs();switchView('discover');toast('Wylogowano. Nadal możesz przeglądać oferty.')}}
function goHome(){switchView(authUser?.role==='admin'?'admin':authUser?.role==='employer'?'employer':'discover')}
function openMapJob(id){document.querySelector('#mapModal').close();setTimeout(()=>openJob(id),100)}
function setupDemoAccounts(){const box=document.createElement('div');box.className='demo-accounts';box.innerHTML='<small>KONTA TESTOWE</small><div><button data-demo="lukasz@example.pl|flexo123">Pracownik</button><button data-demo="firma@flexo.pl|firma123">Pracodawca</button><button data-demo="admin@flexo.pl|admin123">Administrator</button></div>';document.querySelector('#authModal').insertBefore(box,document.querySelector('.auth-security'));box.querySelectorAll('[data-demo]').forEach(button=>button.onclick=()=>{const [email,password]=button.dataset.demo.split('|'),form=document.querySelector('#loginForm');switchAuthTab('login');form.elements.email.value=email;form.elements.password.value=password;form.elements.email.focus()})}
function setupAdminDetails(){const modal=document.createElement('dialog');modal.id='adminDetailsModal';modal.className='admin-details-modal';modal.innerHTML='<button class="modal-close" aria-label="Zamknij">×</button><div id="adminDetailsContent"></div>';document.body.appendChild(modal);modal.querySelector('.modal-close').onclick=()=>modal.close()}
function initMap(){if(typeof L==='undefined'){toast('Mapa nie mogła zostać załadowana. Sprawdź połączenie z internetem.');return}if(!jobsMap){jobsMap=L.map('jobsMap',{zoomControl:true}).setView([userLocation.lat,userLocation.lng],13);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'}).addTo(jobsMap);jobMapLayer=L.layerGroup().addTo(jobsMap);startMarker=L.marker([userLocation.lat,userLocation.lng],{draggable:true,title:'Punkt startowy'}).addTo(jobsMap).bindTooltip('Twój punkt startowy');radiusCircle=L.circle([userLocation.lat,userLocation.lng],{radius:filters.radius*1000,color:'#0d5b48',fillColor:'#bdf5da',fillOpacity:.16,weight:2}).addTo(jobsMap);startMarker.on('dragend',e=>setMapOrigin(e.target.getLatLng()));jobsMap.on('click',e=>setMapOrigin(e.latlng))}setTimeout(()=>{jobsMap.invalidateSize();updateMap()},50)}
function setMapOrigin(pos){userLocation={lat:pos.lat,lng:pos.lng,label:'Wybrany punkt na mapie'};locationFilterEnabled=true;updateMap()}
function clearRoute(){routeRequestId++;if(routeLine&&jobsMap)jobsMap.removeLayer(routeLine);routeLine=null;selectedMapJobId=null;document.querySelector('#routeSummary').hidden=true}
async function drawRouteToJob(id,fit=true){if(!locationFilterEnabled)return toast('Najpierw ustaw punkt startowy lub użyj swojej lokalizacji.');const job=jobs.find(j=>j.id===id);if(!job)return;selectedMapJobId=id;const requestId=++routeRequestId,profiles={walk:'foot',bike:'bike',transit:'car',car:'car'},profile=profiles[travelMode],url=`https://routing.openstreetmap.de/routed-${profile}/route/v1/driving/${userLocation.lng},${userLocation.lat};${job.lng},${job.lat}?overview=full&geometries=geojson`;const modeIcons={walk:'🚶',bike:'🚲',transit:'🚌',car:'🚗'},summary=document.querySelector('#routeSummary');document.querySelector('#routeIcon').textContent=modeIcons[travelMode];document.querySelector('#routeJobName').textContent=job.role;document.querySelector('#routeMeta').textContent='Wyznaczam trasę po drogach…';summary.hidden=false;try{const response=await fetch(url);if(!response.ok)throw new Error('routing');const data=await response.json();if(requestId!==routeRequestId||!data.routes?.length)return;const route=data.routes[0],points=route.geometry.coordinates.map(([lng,lat])=>[lat,lng]);if(routeLine)jobsMap.removeLayer(routeLine);routeLine=L.polyline(points,{color:'#0d5b48',weight:5,opacity:.9}).addTo(jobsMap);let minutes=Math.max(1,Math.round(route.duration/60));if(travelMode==='transit')minutes=Math.round(minutes*1.25+8);const label=travelMode==='transit'?'komunikacją (orientacyjnie)':estimateTravel(job).label;document.querySelector('#routeMeta').textContent=`${(route.distance/1000).toFixed(1).replace('.',',')} km · około ${minutes} min ${label}`;if(fit)jobsMap.fitBounds(routeLine.getBounds().pad(.15),{maxZoom:15})}catch(error){if(requestId!==routeRequestId)return;document.querySelector('#routeMeta').textContent='Nie udało się teraz wyznaczyć trasy. Spróbuj ponownie.';toast('Serwis trasowania jest chwilowo niedostępny.')}}
function clearLocationFilter(){locationFilterEnabled=false;clearRoute();renderJobs();updateMap();toast('Filtrowanie według lokalizacji zostało wyłączone.')}
function updateMap(){if(!jobsMap)return;startMarker.setLatLng([userLocation.lat,userLocation.lng]).setOpacity(locationFilterEnabled?1:.45);radiusCircle.setLatLng([userLocation.lat,userLocation.lng]).setRadius(filters.radius*1000).setStyle({opacity:locationFilterEnabled?1:0,fillOpacity:locationFilterEnabled?0.16:0});jobMapLayer.clearLayers();let count=0;jobs.filter(j=>j.active!==false).forEach(j=>{const within=!locationFilterEnabled||jobDistance(j)<=filters.radius,trip=estimateTravel(j);if(within)count++;const popup=`<div class="map-job-popup"><strong>${j.role}</strong><small>${j.company} · ${j.area}</small><small>${j.date}, ${j.time} · ${j.rate} zł/h</small>${locationFilterEnabled?`<small>${jobDistance(j).toFixed(1).replace('.',',')} km · około ${trip.minutes} min ${trip.label}</small>`:''}<button onclick="openMapJob(${j.id})">Zobacz zlecenie →</button></div>`,marker=L.circleMarker([j.lat,j.lng],{radius:within?9:6,color:within?'#0d5b48':'#8f9c97',fillColor:within?'#d8ff70':'#d9dfdc',fillOpacity:1,weight:2,opacity:within?1:.55,bubblingMouseEvents:false}).addTo(jobMapLayer).bindPopup(popup,{minWidth:190});marker.on('click',()=>drawRouteToJob(j.id,true))});document.querySelector('#mapJobsCount').textContent=count;document.querySelector('#mapLocationLabel').textContent=locationFilterEnabled?userLocation.label:'Nie wybrano';document.querySelector('#mapRadiusOutput').value=filters.radius;document.querySelector('#mapRadius').value=filters.radius;document.querySelector('#mapClearLocation').hidden=!locationFilterEnabled;document.querySelector('#clearLocation').hidden=!locationFilterEnabled;if(selectedMapJobId&&locationFilterEnabled)drawRouteToJob(selectedMapJobId,false)}
function openMap(){document.querySelector('#mapModal').showModal();document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===travelMode));initMap()}
function fitAllMapJobs(){if(!jobsMap)return;const points=jobs.filter(j=>j.active!==false).map(j=>[j.lat,j.lng]);if(locationFilterEnabled)points.push([userLocation.lat,userLocation.lng]);if(points.length)jobsMap.fitBounds(L.latLngBounds(points).pad(.18),{maxZoom:13});toast('Mapa pokazuje wszystkie aktywne oferty.')}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>switchView(b.dataset.view));document.querySelectorAll('.filter[data-filter]').forEach(b=>b.onclick=()=>{activeDate=b.dataset.filter;aiMatchedIds=null;document.querySelectorAll('.filter[data-filter]').forEach(x=>x.classList.toggle('active',x===b));renderJobs()});
document.querySelectorAll('[data-home]').forEach(link=>link.onclick=e=>{e.preventDefault();goHome();history.replaceState(null,'','#')});
document.querySelector('#searchInput').oninput=renderJobs;document.querySelector('#sortSelect').onchange=e=>{filters.sort=e.target.value;renderJobs()};document.querySelector('#filterBtn').onclick=()=>{syncFilterForm();filterModal.showModal()};document.querySelector('#radiusInput').oninput=e=>document.querySelector('#radiusOutput').value=e.target.value;
document.querySelector('#locateBtn').onclick=()=>locateUser(true);document.querySelector('#quickLocate').onclick=()=>locateUser(true);document.querySelector('#clearLocation').onclick=clearLocationFilter;document.querySelector('#clearFilters').onclick=clearFilters;document.querySelector('#filterForm').onsubmit=e=>{e.preventDefault();readFilterForm();filterModal.close();renderJobs()};document.querySelector('#jobModal .modal-close').onclick=()=>jobModal.close();document.querySelector('#mapToggle').onclick=openMap;document.querySelector('#mapModal .modal-close').onclick=()=>document.querySelector('#mapModal').close();document.querySelector('#mapLocate').onclick=()=>locateUser(false);document.querySelector('#mapFitJobs').onclick=fitAllMapJobs;document.querySelector('#mapClearLocation').onclick=clearLocationFilter;document.querySelector('#clearRoute').onclick=clearRoute;document.querySelector('#mapRadius').oninput=e=>{filters.radius=+e.target.value;locationFilterEnabled=true;updateMap()};document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{travelMode=b.dataset.mode;document.querySelectorAll('[data-mode]').forEach(x=>x.classList.toggle('active',x===b));updateMap();renderJobs()});document.querySelector('#applyMapArea').onclick=()=>{document.querySelector('#mapModal').close();renderJobs();toast(locationFilterEnabled?'Obszar wyszukiwania został zaktualizowany.':'Wyniki nie są filtrowane według lokalizacji.')};
document.querySelector('#openAssistant').onclick=openAssistant;document.querySelector('#assistantFab').onclick=openAssistant;document.querySelector('#assistantModal .modal-close').onclick=()=>assistantModal.close();document.querySelector('#assistantForm').onsubmit=e=>{e.preventDefault();const i=document.querySelector('#assistantPrompt'),text=i.value;i.value='';handleAssistant(text)};document.querySelectorAll('.prompt-examples button').forEach(b=>b.onclick=()=>handleAssistant(b.textContent));
document.querySelector('#editProfileBtn').onclick=()=>requireAuth(openProfileEditor);document.querySelector('#profileModal .modal-close').onclick=()=>document.querySelector('#profileModal').close();document.querySelector('.cancel-profile').onclick=()=>document.querySelector('#profileModal').close();document.querySelector('#profileForm').onsubmit=e=>{e.preventDefault();saveProfile(e.target)};
document.querySelector('#addJobBtn').onclick=openNewJob;document.querySelector('#employerAddJobBtn').onclick=openNewJob;document.querySelector('#jobFormModal .modal-close').onclick=()=>document.querySelector('#jobFormModal').close();document.querySelector('.cancel-job').onclick=()=>document.querySelector('#jobFormModal').close();document.querySelector('#adminJobForm').onsubmit=e=>{e.preventDefault();addAdminJob(e.target)};document.querySelector('#adminJobSearch').oninput=renderAdminJobs;document.querySelector('#employerJobSearch').oninput=renderAdminJobs;
document.querySelectorAll('[data-auth-tab]').forEach(b=>b.onclick=()=>switchAuthTab(b.dataset.authTab));document.querySelectorAll('[data-switch-auth]').forEach(b=>b.onclick=()=>switchAuthTab(b.dataset.switchAuth));document.querySelector('#authModal .modal-close').onclick=()=>{pendingAuthAction=null;document.querySelector('#authModal').close()};document.querySelector('#loginForm').onsubmit=e=>{e.preventDefault();login(e.target)};document.querySelector('#registerForm').onsubmit=e=>{e.preventDefault();register(e.target)};document.querySelector('#accountAction').onclick=accountAction;document.querySelector('#mobileAccountAction').onclick=accountAction;
setupDemoAccounts();setupAdminDetails();renderProfile();renderAuthState();renderJobs();renderBooked();renderAdminJobs();if(['employer','admin'].includes(authUser?.role))goHome();

