const jobs = [
  {id:1,role:'Barista / pomoc na sali',company:'Kawa Dobro',icon:'☕',date:'Dzisiaj',day:0,time:'17:00–21:00',start:17,hours:4,rate:30,area:'Śródmieście',lat:52.2318,lng:21.0088,industry:'horeca',match:96,color:'#c9efe0',newness:5,experience:false,sanepid:true,english:false,tasks:['Obsługa gości i wydawanie zamówień','Dbanie o porządek na sali','Proste przygotowanie napojów']},
  {id:2,role:'Obsługa eventu',company:'Hala Koszyki',icon:'✦',date:'Dzisiaj',day:0,time:'18:30–22:30',start:18.5,hours:4,rate:34,area:'Centrum',lat:52.2225,lng:21.0051,industry:'events',match:92,color:'#ffe0cf',newness:6,experience:false,sanepid:false,english:true,tasks:['Witanie i kierowanie gości','Wsparcie szatni','Porządkowanie strefy eventowej']},
  {id:3,role:'Pomoc kuchenna',company:'Zielony Talerz',icon:'🥗',date:'Jutro',day:1,time:'12:00–16:00',start:12,hours:4,rate:29,area:'Mokotów',lat:52.1934,lng:21.0262,industry:'horeca',match:88,color:'#e4efbb',newness:2,experience:true,sanepid:true,english:false,tasks:['Przygotowanie stanowisk','Proste prace kuchenne','Utrzymanie porządku']},
  {id:4,role:'Pracownik sklepu',company:'Lokals',icon:'◼',date:'Jutro',day:1,time:'16:00–20:00',start:16,hours:4,rate:31,area:'Powiśle',lat:52.2360,lng:21.0315,industry:'retail',match:84,color:'#d9ddff',newness:4,experience:false,sanepid:false,english:false,tasks:['Wykładanie produktu','Pomoc klientom','Porządkowanie ekspozycji']},
  {id:5,role:'Host / hostessa',company:'Kino Muranów',icon:'▶',date:'Czwartek',day:2,time:'17:30–21:30',start:17.5,hours:4,rate:32,area:'Muranów',lat:52.2496,lng:20.9938,industry:'events',match:81,color:'#f7d6df',newness:3,experience:true,sanepid:false,english:true,tasks:['Kontrola biletów','Wskazywanie sal','Pomoc przy wydarzeniu']},
  {id:6,role:'Pakowanie zamówień',company:'Paczka Roślin',icon:'⌂',date:'Piątek',day:3,time:'09:00–13:00',start:9,hours:4,rate:28,area:'Wola',lat:52.2310,lng:20.9518,industry:'logistics',match:79,color:'#d8ead8',newness:1,experience:false,sanepid:false,english:false,tasks:['Kompletowanie produktów','Pakowanie paczek','Kontrola etykiet']}
];
let booked=JSON.parse(localStorage.getItem('flexo-booked')||'[1]'),activeDate='all';
let userLocation={lat:52.2297,lng:21.0122,label:'Centrum Warszawy'};
let filters={radius:10,minRate:0,industries:[],time:'all',noExperience:false,noSanepid:false,noEnglish:false,sort:'recommended'};
const grid=document.querySelector('#jobsGrid'),jobModal=document.querySelector('#jobModal'),filterModal=document.querySelector('#filterModal');

function distanceKm(a,b){const R=6371,r=v=>v*Math.PI/180,dLat=r(b.lat-a.lat),dLng=r(b.lng-a.lng),x=Math.sin(dLat/2)**2+Math.cos(r(a.lat))*Math.cos(r(b.lat))*Math.sin(dLng/2)**2;return R*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))}
function jobDistance(j){return distanceKm(userLocation,{lat:j.lat,lng:j.lng})}
function timeMatches(j){return filters.time==='all'||(filters.time==='morning'&&j.start<12)||(filters.time==='afternoon'&&j.start>=12&&j.start<17)||(filters.time==='evening'&&j.start>=17)}
function filteredJobs(){const q=document.querySelector('#searchInput').value.trim().toLowerCase();let list=jobs.filter(j=>(activeDate==='all'||(activeDate==='today'&&j.day===0)||(activeDate==='tomorrow'&&j.day===1))&&(j.role+' '+j.company+' '+j.area).toLowerCase().includes(q)&&jobDistance(j)<=filters.radius&&j.rate>=filters.minRate&&(!filters.industries.length||filters.industries.includes(j.industry))&&timeMatches(j)&&(!filters.noExperience||!j.experience)&&(!filters.noSanepid||!j.sanepid)&&(!filters.noEnglish||!j.english));const sorters={nearest:(a,b)=>jobDistance(a)-jobDistance(b),rate:(a,b)=>b.rate-a.rate,newest:(a,b)=>b.newness-a.newness,recommended:(a,b)=>b.match-a.match};return list.sort(sorters[filters.sort])}
function requirementLabel(j){if(j.sanepid)return 'Sanepid wymagany';if(j.english)return 'Angielski wymagany';return 'Bez doświadczenia'}
function renderJobs(){const list=filteredJobs();document.querySelector('#resultCount').textContent=list.length;grid.innerHTML=list.length?list.map(j=>`<article class="job-card" data-id="${j.id}"><div class="job-cover" style="--cover:${j.color}"><div class="company-logo">${j.icon}</div><span class="match">${j.match}% DOPASOWANIA</span></div><div class="job-body"><h3>${j.role}</h3><span class="company">${j.company} · ${j.area}</span><div class="job-meta"><span>▣ ${j.date}, ${j.time}</span><span>⌖ ${jobDistance(j).toFixed(1).replace('.',',')} km</span><span class="requirement-tag">${requirementLabel(j)}</span></div><div class="job-footer"><div><strong>${j.rate*j.hours} zł</strong><small> · ${j.rate} zł/h</small></div><button>${booked.includes(j.id)?'Zapisano ✓':'Zobacz'}</button></div></div></article>`).join(''):'<div class="empty"><strong>Brak zmian w tym obszarze</strong><br><br>Zwiększ promień lub usuń część filtrów.</div>';document.querySelectorAll('.job-card').forEach(el=>el.onclick=()=>openJob(+el.dataset.id));renderFilterSummary()}
function renderFilterSummary(){const chips=[];if(filters.radius!==10)chips.push(`Do ${filters.radius} km`);if(filters.minRate)chips.push(`Od ${filters.minRate} zł/h`);if(filters.industries.length)chips.push(`${filters.industries.length} branże`);if(filters.time!=='all')chips.push({morning:'Rano',afternoon:'Popołudnie',evening:'Wieczór'}[filters.time]);if(filters.noExperience)chips.push('Bez doświadczenia');if(filters.noSanepid)chips.push('Bez sanepidu');if(filters.noEnglish)chips.push('Bez angielskiego');document.querySelector('#activeFilters').innerHTML=chips.map(x=>`<span class="filter-chip">${x}</span>`).join('');const badge=document.querySelector('#filterCount');badge.textContent=chips.length;badge.classList.toggle('visible',chips.length>0);document.querySelector('#locationLabel').textContent=`${userLocation.label} · do ${filters.radius} km`}
function openJob(id){const j=jobs.find(x=>x.id===id);jobModal.querySelector('#modalContent').innerHTML=`<div class="modal-hero" style="background:${j.color}"><div class="company-logo">${j.icon}</div><p class="eyebrow">${j.match}% DOPASOWANIA · ${jobDistance(j).toFixed(1).replace('.',',')} KM</p><h2>${j.role}</h2><p>${j.company} · ${j.area}</p></div><div class="modal-body"><div class="modal-details"><div class="detail"><small>Kiedy</small><strong>${j.date}<br>${j.time}</strong></div><div class="detail"><small>Wynagrodzenie</small><strong>${j.rate*j.hours} zł<br>${j.rate} zł/h</strong></div></div><h3>Co będziesz robić?</h3><ul>${j.tasks.map(t=>`<li>${t}</li>`).join('')}</ul><p><strong>Wymagania:</strong> ${requirementLabel(j)}</p><button class="book-button" data-book="${j.id}">${booked.includes(j.id)?'Anuluj zapis':'Biorę tę zmianę'}</button></div>`;jobModal.showModal();jobModal.querySelector('[data-book]').onclick=()=>toggleBook(id)}
function toggleBook(id){booked=booked.includes(id)?booked.filter(x=>x!==id):[...booked,id];localStorage.setItem('flexo-booked',JSON.stringify(booked));jobModal.close();renderJobs();renderBooked();toast(booked.includes(id)?'Zmiana jest Twoja! Szczegóły znajdziesz w kalendarzu.':'Zapis na zmianę został anulowany.')}
function renderBooked(){const list=booked.map(id=>jobs.find(j=>j.id===id)).filter(Boolean);document.querySelector('#shiftCount').textContent=list.length;document.querySelector('#bookedList').innerHTML=list.length?list.map(j=>`<article class="booked-card"><div class="date-tile"><small>${j.day===0?'SIE':'JUT'}</small><strong>${j.day===0?'18':'19'}</strong></div><div class="grow"><h3>${j.role}</h3><p>${j.company} · ${j.time} · ${j.area}</p><strong>${j.rate*j.hours} zł</strong></div><button class="primary" onclick="openJob(${j.id})">Szczegóły</button></article>`).join(''):'<div class="empty">Nie masz jeszcze zaplanowanych zmian.</div>'}
function switchView(id){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active-view',v.id===id));document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===id));window.scrollTo({top:0,behavior:'smooth'})}
function toast(msg){const t=document.querySelector('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3200)}
function locateUser(){const status=document.querySelector('#geoStatus');status.textContent='Pobieram lokalizację…';if(!navigator.geolocation){status.textContent='GPS niedostępny';toast('Ta przeglądarka nie obsługuje geolokalizacji.');return}navigator.geolocation.getCurrentPosition(pos=>{userLocation={lat:pos.coords.latitude,lng:pos.coords.longitude,label:'Twoja lokalizacja'};status.textContent=`Lokalizacja dokładna do ${Math.round(pos.coords.accuracy)} m`;renderJobs();toast('Lokalizacja została ustawiona.')},()=>{status.textContent='Brak dostępu do lokalizacji';toast('Zezwól przeglądarce na dostęp do lokalizacji i spróbuj ponownie.')},{enableHighAccuracy:true,timeout:10000,maximumAge:300000})}
function syncFilterForm(){document.querySelector('#radiusInput').value=filters.radius;document.querySelector('#radiusOutput').value=filters.radius;document.querySelector(`[name="rate"][value="${filters.minRate}"]`).checked=true;document.querySelectorAll('[name="industry"]').forEach(x=>x.checked=filters.industries.includes(x.value));document.querySelector('#timeFilter').value=filters.time;document.querySelector('#noExperience').checked=filters.noExperience;document.querySelector('#noSanepid').checked=filters.noSanepid;document.querySelector('#noEnglish').checked=filters.noEnglish}
function readFilterForm(){filters.radius=+document.querySelector('#radiusInput').value;filters.minRate=+document.querySelector('[name="rate"]:checked').value;filters.industries=[...document.querySelectorAll('[name="industry"]:checked')].map(x=>x.value);filters.time=document.querySelector('#timeFilter').value;filters.noExperience=document.querySelector('#noExperience').checked;filters.noSanepid=document.querySelector('#noSanepid').checked;filters.noEnglish=document.querySelector('#noEnglish').checked}
function clearFilters(){filters={...filters,radius:10,minRate:0,industries:[],time:'all',noExperience:false,noSanepid:false,noEnglish:false};syncFilterForm()}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>switchView(b.dataset.view));
document.querySelectorAll('.filter[data-filter]').forEach(b=>b.onclick=()=>{activeDate=b.dataset.filter;document.querySelectorAll('.filter[data-filter]').forEach(x=>x.classList.toggle('active',x===b));renderJobs()});
document.querySelector('#searchInput').oninput=renderJobs;document.querySelector('#sortSelect').onchange=e=>{filters.sort=e.target.value;renderJobs()};
document.querySelector('#filterBtn').onclick=()=>{syncFilterForm();filterModal.showModal()};document.querySelector('#radiusInput').oninput=e=>document.querySelector('#radiusOutput').value=e.target.value;
document.querySelector('#locateBtn').onclick=locateUser;document.querySelector('#quickLocate').onclick=locateUser;document.querySelector('#clearFilters').onclick=clearFilters;
document.querySelector('#filterForm').onsubmit=e=>{e.preventDefault();readFilterForm();filterModal.close();renderJobs()};document.querySelector('#jobModal .modal-close').onclick=()=>jobModal.close();
document.querySelector('#mapToggle').onclick=()=>toast('Widok mapy z pinami ofert będzie dostępny w kolejnej wersji.');renderJobs();renderBooked();

